const express = require("express");
const nodemailer = require("nodemailer");
const { sql, getPool } = require("../db");
const authenticate = require("../middleware/auth");

const router = express.Router();

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL_USER
      ? process.env.EMAIL_USER.trim().replace(/\r/g, "")
      : "",
    pass: process.env.EMAIL_PASS
      ? process.env.EMAIL_PASS.trim().replace(/\r/g, "").replace(/\s+/g, "")
      : "",
  },
});

router.get("/api/users", authenticate, async (req, res) => {
  try {
    const pool = await getPool();
    const result = await pool
      .request()
      .query(
        "SELECT Id, Name, Role, Email, Phone, Password, Force_Password, CreatedBy, CreatedDate, UpdatedBy, UpdatedDate FROM Users ORDER BY Id DESC",
      );
    res.json(result.recordset);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.post("/api/users", authenticate, async (req, res) => {
  const { name, role, email, phone, password, forcePassword } = req.body;
  const creatorRole = req.user.role;
  const creatorId = Number(req.user.id) || null;

  const creatorRoleUpper = (creatorRole || "").toUpperCase();
  const targetRoleUpper = (role || "").toUpperCase();
  if (creatorRoleUpper === "TEACHER" && targetRoleUpper !== "STUDENT") {
    return res.status(403).json({ error: "Teachers can only create Students" });
  }
  if (creatorRoleUpper !== "HEADMASTER" && creatorRoleUpper !== "TEACHER") {
    return res.status(403).json({ error: "Access denied" });
  }

  if (!name || !role || !email) {
    return res
      .status(400)
      .json({ error: "Name, Role, and Email are required" });
  }

  let userPassword = password;
  let isAutoGenerated = false;
  if (!userPassword || !userPassword.trim() ) {
    isAutoGenerated = true;
    const chars =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#%^*";
    let generated = "";
    for (let i = 0; i < 8; i++) {
      generated += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    userPassword = generated;
  }

  try {
    const pool = await getPool();

    const check = await pool
      .request()
      .input("email", sql.NVarChar, email.trim())
      .query("SELECT Id FROM Users WHERE LOWER(Email) = LOWER(@email)");
    if (check.recordset.length > 0) {
      return res.status(400).json({ error: "Email is already registered" });
    }

    const forceVal = forcePassword || isAutoGenerated ? "Y" : "N";

    const result = await pool
      .request()
      .input("name", sql.NVarChar, name.trim())
      .input("role", sql.NVarChar, role)
      .input("email", sql.NVarChar, email.trim())
      .input("phone", sql.NVarChar, phone ? phone.trim() : null)
      .input("password", sql.NVarChar, userPassword)
      .input("forcePassword", sql.NVarChar, forceVal)
      .input("createdBy", sql.Int, creatorId)
      .input("createdDate", sql.DateTime, new Date()).query(`
        INSERT INTO Users (Name, Role, Email, Phone, Password, Force_Password, CreatedBy, CreatedDate, IsTempPassword)
        OUTPUT INSERTED.Id
        VALUES (@name, @role, @email, @phone, @password, @forcePassword, @createdBy, GETUTCDATE(), 0)
      `);

    const newUserId = result.recordset[0].Id;

    if (targetRoleUpper === "TEACHER") {
      await pool
        .request()
        .input("userId", sql.Int, newUserId)
        .query("INSERT INTO matrix (user_id, level) VALUES (@userId, 1)");
    } else if (targetRoleUpper === "HEADMASTER") {
      await pool
        .request()
        .input("userId", sql.Int, newUserId)
        .query("INSERT INTO matrix (user_id, level) VALUES (@userId, 2)");
    }

    const appUrl = process.env.APP_URL || "http://localhost:5173";
    transporter.sendMail({
      from: process.env.EMAIL_USER,
      to: email.trim(),
      subject: "🎒 Account Created - Student Management System",
      html: `
        <div style="font-family: Arial, sans-serif; background: #f4f6ff; padding: 30px;">
          <div style="max-width: 480px; margin: 0 auto; background: #fff; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 24px rgba(102,126,234,0.15);">
            <div style="background: linear-gradient(135deg, #667eea, #764ba2); padding: 28px; text-align: center;">
              <div style="font-size: 40px;">🎒</div>
              <h2 style="color: #fff; margin: 8px 0 4px; font-size: 20px;">Welcome to SMS</h2>
              <p style="color: rgba(255,255,255,0.8); margin: 0; font-size: 13px;">Your account has been created</p>
            </div>
            <div style="padding: 32px;">
              <p style="color: #444; font-size: 15px;">Hello <strong>${name.trim()}</strong>,</p>
              <p style="color: #666; font-size: 14px;">A Headmaster has created an account for you on the Student Management System.</p>
              
              <div style="background: #f7f9fc; border-radius: 12px; padding: 20px; margin: 20px 0; border: 1px solid #eef2f5;">
                <div style="margin-bottom: 10px; font-size: 14px; color: #555;">
                  <strong>Email:</strong> ${email.trim()}
                </div>
                <div style="font-size: 14px; color: #555;">
                  <strong>Temporary Password:</strong> <code style="background: #eef2f5; padding: 3px 6px; border-radius: 4px; font-family: monospace; font-size: 14px; color: #667eea;">${userPassword}</code>
                </div>
              </div>

              <div style="text-align: center; margin: 25px 0;">
                <a href="${appUrl}" style="background: linear-gradient(135deg, #667eea, #764ba2); color: #fff; text-decoration: none; padding: 12px 28px; border-radius: 8px; font-weight: bold; display: inline-block; box-shadow: 0 4px 12px rgba(102,126,234,0.3);">
                  Go to Login
                </a>
              </div>

              <p style="color: #c81e1e; font-size: 13px; font-weight: 600; text-align: center;">
                ⚠️ You will be prompted to change your password immediately upon first login.
              </p>
            </div>
          </div>
        </div>
      `,
    }).catch((mailErr) => {
      console.warn("New user welcome email skipped:", mailErr.message);
    });

    res
      .status(201)
      .json({ success: true, message: "User created successfully" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.put("/api/users/:id", authenticate, async (req, res) => {
  const { name, role, email, phone } = req.body;
  const editorRole = req.user.role;
  const editorId = Number(req.user.id) || null;
  const targetId = req.params.id;

  const editorRoleUpper = (editorRole || "").toUpperCase();
  const targetRoleUpper = (role || "").toUpperCase();

  if (editorRoleUpper !== "HEADMASTER" && editorRoleUpper !== "TEACHER") {
    return res.status(403).json({ error: "Access denied" });
  }

  try {
    const pool = await getPool();

    const targetRes = await pool
      .request()
      .input("id", sql.Int, targetId)
      .query("SELECT * FROM Users WHERE Id = @id");

    if (targetRes.recordset.length === 0) {
      return res.status(404).json({ error: "User not found" });
    }

    const targetUser = targetRes.recordset[0];

    if (editorRoleUpper === "TEACHER") {
      const targetUserRoleUpper = (targetUser.Role || "").toUpperCase();
      if (targetUserRoleUpper !== "STUDENT" || targetRoleUpper !== "STUDENT") {
        return res
          .status(403)
          .json({ error: "Teacher can only edit and manage Students" });
      }
    }

    if (email.trim().toLowerCase() !== targetUser.Email.toLowerCase()) {
      const check = await pool
        .request()
        .input("email", sql.NVarChar, email.trim())
        .query("SELECT Id FROM Users WHERE LOWER(Email) = LOWER(@email)");
      if (check.recordset.length > 0) {
        return res
          .status(400)
          .json({ error: "Email is already registered by another user" });
      }
    }

    await pool
      .request()
      .input("id", sql.Int, targetId)
      .input("name", sql.NVarChar, name.trim())
      .input("role", sql.NVarChar, role)
      .input("email", sql.NVarChar, email.trim())
      .input("phone", sql.NVarChar, phone ? phone.trim() : null)
      .input("updatedBy", sql.Int, editorId).query(`
        UPDATE Users 
        SET Name=@name, Role=@role, Email=@email, Phone=@phone,
            UpdatedBy=@updatedBy, UpdatedDate=GETUTCDATE()
        WHERE Id=@id
      `);

    await pool
      .request()
      .input("userId", sql.Int, targetId)
      .query("DELETE FROM matrix WHERE user_id = @userId");

    if (targetRoleUpper === "TEACHER") {
      await pool
        .request()
        .input("userId", sql.Int, targetId)
        .query("INSERT INTO matrix (user_id, level) VALUES (@userId, 1)");
    } else if (targetRoleUpper === "HEADMASTER") {
      await pool
        .request()
        .input("userId", sql.Int, targetId)
        .query("INSERT INTO matrix (user_id, level) VALUES (@userId, 2)");
    }

    res.json({ success: true, message: "User updated successfully" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.delete("/api/users/:id", authenticate, async (req, res) => {
  const editorRole = req.user.role;
  const editorId = req.user.id;
  const targetId = req.params.id;

  const editorRoleUpper = (editorRole || "").toUpperCase();

  if (editorRoleUpper !== "HEADMASTER" && editorRoleUpper !== "TEACHER") {
    return res.status(403).json({ error: "Access denied" });
  }

  if (Number(editorId) === Number(targetId)) {
    return res
      .status(400)
      .json({ error: "You cannot delete your own account" });
  }

  try {
    const pool = await getPool();

    const targetRes = await pool
      .request()
      .input("id", sql.Int, targetId)
      .query("SELECT * FROM Users WHERE Id = @id");

    if (targetRes.recordset.length === 0) {
      return res.status(404).json({ error: "User not found" });
    }

    const targetUser = targetRes.recordset[0];
    const targetUserRoleUpper = (targetUser.Role || "").toUpperCase();
    if (editorRoleUpper === "TEACHER" && targetUserRoleUpper !== "STUDENT") {
      return res
        .status(403)
        .json({ error: "Teacher can only delete Students" });
    }

    await pool
      .request()
      .input("id", sql.Int, targetId)
      .query("DELETE FROM Users WHERE Id = @id");

    res.json({ success: true, message: "User deleted successfully" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
